steps:
  # React フロントエンドのビルドのみ
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/portfolio-egg-repo/portfolio-egg-frontend',
      '--build-arg', 'VITE_API_URL=https://portfolio-egg-api-x32mqmvn7q-an.a.run.app',
      '--build-arg', 'VITE_FIREBASE_API_KEY=${_FIREBASE_API_KEY}',
      '--build-arg', 'VITE_FIREBASE_AUTH_DOMAIN=${_FIREBASE_AUTH_DOMAIN}',
      '--build-arg', 'VITE_FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID}',
      '--build-arg', 'VITE_FIREBASE_STORAGE_BUCKET=${_FIREBASE_STORAGE_BUCKET}',
      '--build-arg', 'VITE_FIREBASE_MESSAGING_SENDER_ID=${_FIREBASE_MESSAGING_SENDER_ID}',
      '--build-arg', 'VITE_FIREBASE_APP_ID=${_FIREBASE_APP_ID}',
      './portfolio-egg-frontend'
    ]

  # イメージをプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/portfolio-egg-repo/portfolio-egg-frontend']

  # React フロントエンドをCloud Runにデプロイ
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'portfolio-egg-frontend',
      '--image', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/portfolio-egg-repo/portfolio-egg-frontend',
      '--platform', 'managed',
      '--region', '${_REGION}',
      '--allow-unauthenticated',
      '--port', '8080'
    ]

substitutions:
  _REGION: asia-northeast1

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/portfolio-egg-repo/portfolio-egg-frontend' 