default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: localhost

development:
  <<: *default
  database: portfolio_egg_api_development

test:
  <<: *default
  database: portfolio_egg_api_test

production:
  <<: *default
  database: <%= ENV["PRODUCTION_DB_NAME"] || "portfolio_egg_production" %>
  username: <%= ENV["PRODUCTION_DB_USERNAME"] || "portfolio_user" %>
  password: <%= Rails.application.credentials.gcp&.dig(:db_password) %>
  host: <%= ENV.fetch("DB_SOCKET_DIR", "/cloudsql") %>/<%= ENV["CLOUD_SQL_CONNECTION_NAME"] %>
